name: Analise Estatica (SAST)

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: instalar depencencias
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Instalar depencencias
        run: pip install requirements.txt
      - name: Executar SAST
        run: bandit -r . -f custom
  appscan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions-checkout@v2
      - name: Instalar dependencias e executar aplicacao
        run: |
          pip install -r requirements.txt
          nohup python3 app.py &       
          sleep 5 # Espere servidor iniciar
      - name: HCL-TECH-SOFTWARE/appscan-dast-action@v1.0.7
        with:
          baseurl: "https://cloud.appscan.com"
          target: "http://localhost:5000"
          api_key: ${{ secrets.APPSCAN_API_KEYID }}
          api_secret: ${{ secrets.APPSCAN_API_SECRET }}
          application_id: 1392fcd5-bd11-406c-b1ec-a334a963e705

